development:
 adapter: postgresql
 database: prelaunchr_development
 host: localhost
 username: nader
 password: nader
test:
 adapter: postgresql
 database: prelaunchr_test
 host: localhost
 username: nader
 password: nader
